name: 📺 Update Show Status

on:
  schedule:
    # Every Monday at 3:00 AM CET/CEST
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  update-show-status:
    name: ⬣ Update Show Status
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: 📥 Download deps
        run: pnpm install --frozen-lockfile
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: ✨ Update Show Status
        run: pnpm run update:show:status
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SESSION_SECRET: "unused"
          FLIPT_URL: ${{ vars.FLIPT_URL }}
          FLIPT_TOKEN: ${{ secrets.FLIPT_TOKEN }}
          FLIPT_ENVIRONMENT: ${{ vars.FLIPT_ENVIRONMENT }}
